import 'dart:async';
import 'package:flutter/material.dart';
import '../models/domain.dart';
import '../state/farm_state.dart';
import '../theme/gau_theme.dart';
import '../widgets/app_widgets.dart';
import 'home_screens.dart';

class ScanScreen extends StatefulWidget { const ScanScreen({super.key, required this.state, this.cow}); final FarmState state; final Cow? cow; @override State<ScanScreen> createState() => _ScanScreenState(); }
class _ScanScreenState extends State<ScanScreen> {
  late Cow? _selected = widget.cow; final _tag = TextEditingController();
  @override void dispose() { _tag.dispose(); super.dispose(); }
  void _locate() { final match = widget.state.cowByTag(_tag.text.trim()); if (match == null) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('No cow with this tag on your farm.'))); } else { setState(() => _selected = match); } }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Start milking')), body: ListView(padding: const EdgeInsets.all(22), children: [
    const ProgressStrip(step: 3), const SizedBox(height: 18), const Text('Identify the cow', style: TextStyle(fontSize: 28, fontWeight: FontWeight.w900)), const SizedBox(height: 8), const Text('Scan a QR or RFID tag. In this demo, enter a tag or select a cow.'), const SizedBox(height: 22),
    Container(height: 170, decoration: BoxDecoration(color: GauColors.ink, borderRadius: BorderRadius.circular(27)), child: const Center(child: Column(mainAxisSize: MainAxisSize.min, children: [Icon(Icons.qr_code_scanner, color: GauColors.white, size: 62), SizedBox(height: 8), Text('Simulated QR / RFID reader', style: TextStyle(color: GauColors.white, fontWeight: FontWeight.w800))]))),
    const SizedBox(height: 16), Row(children: [Expanded(child: TextField(controller: _tag, decoration: const InputDecoration(hintText: 'Enter tag, e.g. COW-024'))), const SizedBox(width: 8), IconButton.filled(onPressed: _locate, icon: const Icon(Icons.arrow_forward))]), const SizedBox(height: 12),
    Wrap(spacing: 7, children: widget.state.cows.map((cow) => ChoiceChip(label: Text('${cow.name} • ${cow.tag}'), selected: _selected == cow, onSelected: (_) => setState(() => _selected = cow))).toList()), const SizedBox(height: 20),
    if (_selected == null) const AppHint(icon: Icons.info_outline, message: 'Verify a cow before simulated sensor data is attached.') else _ConfirmedCow(cow: _selected!), const SizedBox(height: 15),
    PrimaryButton(label: _selected == null ? 'Verify a cow first' : 'Associate sensor and begin', icon: Icons.sensors, onPressed: _selected == null ? null : () { widget.state.startDemoSession(_selected!); Navigator.push(context, MaterialPageRoute(builder: (_) => MilkingSessionScreen(state: widget.state, cow: _selected!))); }),
  ]));
}
class _ConfirmedCow extends StatelessWidget { const _ConfirmedCow({required this.cow}); final Cow cow; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(15), decoration: BoxDecoration(color: GauColors.mint, borderRadius: BorderRadius.circular(19)), child: Row(children: [CowAvatar(cow: cow), const SizedBox(width: 11), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('${cow.name} verified', style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w900)), Text('${cow.tag} • ${cow.breed}')])), const Icon(Icons.verified, color: GauColors.forest)])); }

class MilkingSessionScreen extends StatefulWidget { const MilkingSessionScreen({super.key, required this.state, required this.cow}); final FarmState state; final Cow cow; @override State<MilkingSessionScreen> createState() => _MilkingSessionScreenState(); }
class _MilkingSessionScreenState extends State<MilkingSessionScreen> { bool _running = false; double _progress = 0; Timer? _timer; void _start() { setState(() => _running = true); _timer = Timer.periodic(const Duration(milliseconds: 450), (timer) { if (!mounted) return; setState(() => _progress += .16); if (_progress >= 1) { timer.cancel(); Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => AnalysisScreen(state: widget.state, cow: widget.cow))); } }); } @override void dispose() { _timer?.cancel(); super.dispose(); }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('Milking session')), body: Padding(padding: const EdgeInsets.all(22), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const ProgressStrip(step: 4), const SizedBox(height: 22), Text('${widget.cow.name} is verified', style: const TextStyle(fontSize: 28, fontWeight: FontWeight.w900)), const SizedBox(height: 8), Text('Tag ${widget.cow.tag} • NODE-03 is assigned to this demo session.'), const SizedBox(height: 26), const AppHint(icon: Icons.science_outlined, message: 'Simulated sensor data: milk yield, conductivity, temperature and activity are attached to this cow.'), const SizedBox(height: 25), if (!_running) ...[Container(width: double.infinity, padding: const EdgeInsets.all(27), decoration: BoxDecoration(color: GauColors.white, borderRadius: BorderRadius.circular(25)), child: const Column(children: [Icon(Icons.sensors, color: GauColors.forest, size: 54), SizedBox(height: 10), Text('Demo sensor ready', style: TextStyle(fontSize: 20, fontWeight: FontWeight.w900)), SizedBox(height: 5), Text('You can put the phone aside after starting.', textAlign: TextAlign.center)])), const Spacer(), PrimaryButton(label: 'Start simulated milking', icon: Icons.play_arrow, onPressed: _start)] else ...[const SizedBox(height: 38), Center(child: SizedBox(height: 132, width: 132, child: CircularProgressIndicator(value: _progress, strokeWidth: 10, color: GauColors.forest))), const SizedBox(height: 25), const Center(child: Text('Collecting simulated readings…', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w800)))]])));
}

class AnalysisScreen extends StatefulWidget { const AnalysisScreen({super.key, required this.state, required this.cow}); final FarmState state; final Cow cow; @override State<AnalysisScreen> createState() => _AnalysisScreenState(); }
class _AnalysisScreenState extends State<AnalysisScreen> { @override void initState() { super.initState(); _analyze(); } Future<void> _analyze() async { await Future<void>.delayed(const Duration(milliseconds: 300)); await widget.state.completeSessionPrediction(widget.cow); if (mounted) Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => RiskResultScreen(state: widget.state, cow: widget.cow))); } @override Widget build(BuildContext context) => const Scaffold(body: LoadingState(label: 'Creating an early-warning risk estimate…')); }

class RiskResultScreen extends StatelessWidget { const RiskResultScreen({super.key, required this.state, required this.cow}); final FarmState state; final Cow cow; @override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: ListView(padding: const EdgeInsets.all(22), children: [const SizedBox(height: 15), const Text('Analysis complete', style: TextStyle(color: GauColors.forest, fontWeight: FontWeight.w800)), const SizedBox(height: 5), Text('${cow.name} needs attention', style: const TextStyle(fontSize: 31, fontWeight: FontWeight.w900)), const SizedBox(height: 22), Container(padding: const EdgeInsets.all(24), decoration: BoxDecoration(color: GauColors.red, borderRadius: BorderRadius.circular(30)), child: const Column(children: [Icon(Icons.warning_amber_rounded, color: GauColors.white, size: 57), SizedBox(height: 8), Text('High early-warning risk', style: TextStyle(color: GauColors.white, fontSize: 27, fontWeight: FontWeight.w900)), SizedBox(height: 4), Text('Prototype risk score: 78 / 100', style: TextStyle(color: Colors.white70)), SizedBox(height: 4), Text('Increasing compared with recent sessions', style: TextStyle(color: Colors.white70))])), const SizedBox(height: 20), const SectionHeader('What changed'), const _Factor(icon: Icons.water_drop_outlined, text: 'Milk yield is lower than usual'), const _Factor(icon: Icons.show_chart, text: 'Milk conductivity is increasing'), const _Factor(icon: Icons.directions_walk_outlined, text: 'Activity is lower than usual'), const SizedBox(height: 18), const AppHint(icon: Icons.medical_information_outlined, message: 'This is a prototype early-warning risk estimate, not a diagnosis. Check for visible signs and contact a veterinarian if symptoms are present.', color: Color(0xFFF8EBD4)), PrimaryButton(label: 'Save result and view dashboard', onPressed: () { state.savePrototypeResult(cow); Navigator.pushAndRemoveUntil(context, MaterialPageRoute(builder: (_) => HomeScreen(state: state)), (_) => false); }), const SizedBox(height: 8), Center(child: TextButton(onPressed: () => Navigator.pop(context), child: const Text('Back to simulated readings')))])));
}
class _Factor extends StatelessWidget { const _Factor({required this.icon, required this.text}); final IconData icon; final String text; @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.only(bottom: 11), child: Row(children: [Container(padding: const EdgeInsets.all(8), decoration: BoxDecoration(color: const Color(0xFFF7E6E4), borderRadius: BorderRadius.circular(11)), child: Icon(icon, color: GauColors.red)), const SizedBox(width: 10), Expanded(child: Text(text, style: const TextStyle(fontWeight: FontWeight.w800)))])); }
